[project]
name = "mcp-sse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "fastapi>=0.115.12",
    "fastmcp>=2.1.2",
    "loguru>=0.7.3",
    "mcp>=1.6.0",
    "uvicorn>=0.34.1",
]
